[package]
name = "subtitle_tonemap"
version = "0.2.1"
authors = ["quietvoid"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
image = "0.22.3"
rayon = "1.2.0"
